// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ServicioWebApiUser.Models;

#nullable disable

namespace ServicioWebApiUser.Migrations
{
    [DbContext(typeof(DbContextInnovaTel))]
    [Migration("20240714191033_DatosPedidoVenta")]
    partial class DatosPedidoVenta
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ServicioWebApiUser.Models.Cliente", b =>
                {
                    b.Property<string>("IdCliente")
                        .HasColumnType("varchar(10)");

                    b.Property<string>("DirreccionCliente")
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NombreCliente")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TelefonoCliente")
                        .HasColumnType("nvarchar(15)");

                    b.HasKey("IdCliente");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("ServicioWebApiUser.Models.DetallePedido", b =>
                {
                    b.Property<int>("IdDetalle")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdDetalle"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<int>("IdPedido")
                        .HasColumnType("int");

                    b.Property<int>("IdProducto")
                        .HasColumnType("int");

                    b.Property<double>("Precio")
                        .HasColumnType("float");

                    b.HasKey("IdDetalle");

                    b.ToTable("DetallePedidos");
                });

            modelBuilder.Entity("ServicioWebApiUser.Models.OrdenPedido", b =>
                {
                    b.Property<int>("IdPedido")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPedido"));

                    b.Property<string>("CondicionesPago")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("IdCliente")
                        .HasColumnType("varchar(10)");

                    b.Property<double?>("ImpuestosTotales")
                        .HasColumnType("float");

                    b.Property<DateTime>("fechaventa")
                        .HasColumnType("Date");

                    b.HasKey("IdPedido");

                    b.ToTable("OrdenPedidos");
                });

            modelBuilder.Entity("ServicioWebApiUser.Models.Producto", b =>
                {
                    b.Property<int>("IdProducto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdProducto"));

                    b.Property<string>("CodigoProducto")
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("NombreProducto")
                        .HasColumnType("nvarchar(50)");

                    b.Property<double?>("PrecioProducto")
                        .HasColumnType("float");

                    b.HasKey("IdProducto");

                    b.ToTable("Productos");
                });
#pragma warning restore 612, 618
        }
    }
}
